### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by erisam** [braskamin/thunderbuddy#1]
Föreslår att vi kör Circle CI (och kanske lite TDD?).

Är sugen på att testa Circle CI:
https://circleci.com/

Running CircleCI on Pull Request  - Continuous Integration P3: https://www.youtube.com/watch?v=iPKfeTWBGvU

**Comment by tingvarsson** [comment]
Som Travis CI typ gissar jag?

**Comment by erisam** [comment]
Körs nu på master:
https://circleci.com/gh/braskamin

Stänger issuen.
